services:
  mysql:
    image: mysql:8.4
    container_name: envlab-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: envlab
      MYSQL_USER: envlab_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
